SCIENTISTS = [
    "The Wright Brothers",
    "Robert Evans",
    "Tycho Brahe",
    "Arno Penzias",
    "Klim Churyumov",
    "Galileo Galilei",
    "Hennig Brand",
    "René Descartes",
    "William Harvey",
    "John Dalton",
    "Georges Cuvier",
    "Marie Curie",
    "Isaac Newton",
    "Giovanni Borelli",
    "Michael Faraday",
    "Hans Oersted",
    "Richard Trevithick",
    "Johannes Kepler",
    "Joseph Priestley",
    "Charles Darwin",
    "Humphry Davy",
    "Thomas Fowler",
    "Edwin Hubble",
    "Claudius Galen",
    "William Perkin",
    "Robert Remak",
    "James Thomas Wilson",
    "Comte de Buffon",
    "Alessandro Volta",
    "Antonio Lavoisier",
    "James Watt",
    "Santiago Ramón y Cajal",
    "Robert Hooke",
    "Sigmund Freud",
    "Joseph Thomson",
    "Hans Sloane",
    "Alexander Humboldt",
    "Jean-Martin Charcot",
    "Alfred Wegner",
    "Andreas Vasalius",
    "Simon Stevin",
    "Burrhus Federic",
    "Luigi Galvani",
    "William Shockley",
    "Robert Chambers",
    "Horace Bénédict de Saussure",
    "Ahmed Zewail",
    "Jeffrey Connor Hall",
    "Maria Goeppert Mayer",
    "Ibn AlHaytham",
    "Hussein Ibn Sina",
    "Yoshinori Ohsumi",
    "Harvey J. Alter",
    "Roger Penrose",
    "Michael Rosbash",
    "Michael W. Young",
    "Reinhard Genzel",
    "Andrea M. Ghez",
    "Michael Houghton",
    "Charles M. Rice",
    "Benjamin List",
    "Klaus Hasselmann",
    "David MacMillan",
    "Syukuro Manabe",
    "Giorgio Parisi",
    "James Watson",
    "Francis Crick",
    "Maurice Wilkins",
    "Jacques Dubochet",
    "Joachim Frank",
    "Richard Henderson",
    "Thomas Young",
    "Claude Bernard",
]
